spring:
  application:
    name: sob-blog
  datasource:
    url: jdbc:mysql://49.232.159.4:3344/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8080

