# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8&amp;serverTimezone=CST
    username: root
    password: root

